### ISSUE TITLE
Atom Featurization Code

### ISSUE THREAD

**Issue by lilleswing** [gnina/models#1]
https://arxiv.org/abs/1612.02751

Does the code for atom level featurization exist here?  I want to reproduce the 18 different atom types described in the paper.

I also checked https://github.com/dkoes/rdkit-scripts but was not able to find anything for atom labels.

Thanks!

**Comment by dkoes** [comment]
I assume you figured it out?  Beyond the default atom types, you can also provide custom mappings from smina atom types to the atom types to be used by the cnn with --cnn_recmap and --cnn_ligmap
