### ISSUE TITLE
gnina scores on CrossDocked2020 dataset

### ISSUE THREAD

**Issue by rmwu** [gnina/models#15]
Hello! Thanks for these very useful datasets. I notice that the Vina scores are included in the types files, so I was wondering whether the gnina scores (or any of the various models' scores from the CrossDocked2020 paper) are available for download anywhere, for the provided poses? It seems a bit computationally heavy to recreate them :')

**Comment by francoep** [comment]
Download the [paper_data.tar.gz](http://bits.csb.pitt.edu/files/crossdock2020/v1.0/paper_data.tar.gz)  (this is a 14GB file) & extract it. This will create a directory structure of data/<header>/<files>.

To get the Default2018 predictions you'll care about  `data/cross/it2_crossdocked_DEF2018_s<seed>.<fold>.predictions` files. There are 5 seeds (0-4) and 3 folds (0-2).

To get the dense predictions you'll want `data/dense/predict_s<seed>.predictions` Again, there are 5 seeds.

The format of the files is `<pose score> <pred affinity> | <types file line>`.  You can match the types line with the receptor file and the ligand file sections in `<types file line>`.

**Comment by francoep** [comment]
Note -- these are the predictions for the clustered cross-validated training experiments for the data. There is no predictions available for the deployed version of the models (which are trained on all of the available data rather than a clustered subset)

**Comment by rmwu** [comment]
Thank you for pointing me in the right direction!
