### ISSUE TITLE
What is your model architecture?

### ISSUE THREAD

**Issue by xuzhang5788** [gnina/models#2]
In your paper, you said "five 3 × 3 × 3 convolutional layers with rectified linear activation units alternating with max pooling layers". Is it possible to show a picture of each layer's parameters?

Your model with the mashes 48x48x48 in 34 channels. It is a huge model. How big of your memory is? In total, how many parameters of your model? I am interested in your model details. Many thanks.

**Comment by dkoes** [comment]
I believe you are referring to the initial model that was optimized in the JCIM paper.  Slide 22 of this presentation shows a diagram of it: 
http://bits.csb.pitt.edu/files/CNN_Scoring_ACS_March_2017.pd

f

**Comment by xuzhang5788** [comment]
Thank you very much.

**Comment by SanFran-Me** [comment]
> I believe you are referring to the initial model that was optimized in the JCIM paper. Slide 22 of this presentation shows a diagram of it: http://bits.csb.pitt.edu/files/CNN_Scoring_ACS_March_2017.pd
> 
> f

**Hello, I also want to see the slide in this link but it is 404 Not Found now...**

**Comment by dkoes** [comment]
You are missing the f in pdf.
