### ISSUE TITLE
Several versions of the same receptor in CrossDocked2020

### ISSUE THREAD

**Issue by josejimenezluna** [gnina/models#20]
Hi, 

Many thanks for curating the CrossDocked2020 dataset - it is super useful for our research. I have encountered some issues when exploring the data - namely the same receptor (with same pdbid, and containing the same chain) seems to be present in the same pocket folder.

For instance, consider the `CP3A4_HUMAN_23_503_catalytic_0/4k9t_A_rec.pdb` file:

```
REMARK Selection 'protein or ion and not water'
ATOM      1  N   SER A  29     -12.659  -8.898 -14.390  1.00 73.82         A N
ATOM      2  CA  SER A  29     -13.741  -7.890 -14.636  1.00 72.94         A C
ATOM      3  C   SER A  29     -13.883  -7.497 -16.117  1.00 72.83         A C
ATOM      4  O   SER A  29     -14.937  -6.970 -16.533  1.00 71.08         A O
ATOM      5  CB  SER A  29     -13.479  -6.630 -13.815  1.00 72.53         A C
ATOM      6  OG  SER A  29     -12.680  -5.708 -14.551  1.00 72.01         A O
ATOM      7  N   HIS A  30     -12.824  -7.741 -16.895  1.00 69.18         A N
ATOM      8  CA  HIS A  30     -12.738  -7.273 -18.287  1.00 66.60         A C
...
```

Compared to the `CP3A4_HUMAN_23_503_catalytic_0/4k9t_rec.pdb` file:

```
REMARK Selection '(protein and ch... and not water)'
ATOM      1  N   SER A  29     -26.772   9.141 -14.685  1.00 73.82           N
ATOM      2  CA  SER A  29     -25.634   8.216 -14.991  1.00 72.94           C
ATOM      3  C   SER A  29     -25.499   7.888 -16.489  1.00 72.83           C
ATOM      4  O   SER A  29     -24.423   7.446 -16.946  1.00 71.08           O
ATOM      5  CB  SER A  29     -25.794   6.911 -14.214  1.00 72.53           C
ATOM      6  OG  SER A  29     -26.549   5.967 -14.969  1.00 72.01           O
ATOM      7  N   HIS A  30     -26.590   8.091 -17.236  1.00 69.18           N
ATOM      8  CA  HIS A  30     -26.677   7.670 -18.642  1.00 66.60           C
ATOM      9  C   HIS A  30     -25.903   8.521 -19.613  1.00 68.46           C
```

Coordinates seem to change between these two. Ions also seem to be preserved on the first one - albeit I do not know if this was also done on the second due to the truncation of the `REMARK` field.

What is the difference between these files, and which one of them was used for docking?

Cheers,

**Comment by francoep** [comment]
The second file is not used during training, and is a remnant of the data cleaning pipeline. The receptor files that were used during training/docking are all of the format <pdbid>_<main chain>_rec.pdb.

Notably, this <main_chain> property was determined via pocketome, and is not necessarily all of the chains present in the structure as the binding site could be made from a complex of multiple chains.  That being said, there are instances of duplicate chains -- i.e. where pocketome has identified different chains of the same protein that contain the same binding complex information. We have not removed those redundancies in the current release of Pocketome (but they are among the next series of changes that we are addressing with the next release).

**Comment by josejimenezluna** [comment]
Fantastic, many thanks for the quick reply!
