### ISSUE TITLE
Asking access to URL of crossdock2020

### ISSUE THREAD

**Issue by DongkiKim95** [gnina/models#22]
Hi,

Thanks a lot for curating CrossDocked2020 and PDBBind.

Currently, the URL is not available: [http://bits.csb.pitt.edu/files/crossdock2020/](http://bits.csb.pitt.edu/files/crossdock2020/)

Could you please check it out?

**Comment by dkoes** [comment]
Yes, we lost internet connectivity at 10pm last night.  The appropriate people are aware of the issue and hopefully it will be fixed soon.

**Comment by DongkiKim95** [comment]
Thank you very much.
