### ISSUE TITLE
‘CrossDocked2020_v1.2.tgz’ archive is corrupt

### ISSUE THREAD

**Issue by Fx-Ren** [gnina/models#23]
An error is reported during file decompression.

Archive File：CrossDocked2020_v1.2.tgz
Error Message in Linux：
![image](https://user-images.githubusercontent.com/17877321/190036298-285f3648-40cc-4fbb-905c-e8c4e03b47ba.png)

Error Message in Windows：
![image](https://user-images.githubusercontent.com/17877321/190036394-4b77d015-9b4e-4210-a24c-6097583c92de.png)

**Comment by Fx-Ren** [comment]
How much storage space is occupied after decompression?

**Comment by francoep** [comment]
The unpacked directory is 756GB uncompressed. If you are working with libmolgrid you can utilize the molcaches & types files without having to unpack the contents of the huge tarball.

**Comment by Jsm34** [comment]
[@]()![image](https://github.com/gnina/models/assets/104213558/12cdf160-876a-4276-b64e-0684f4cb53d9)
