### ISSUE TITLE
‘CrossDocked2020_v1.2.tgz’ archive is corrupt，how to solve the problem?

### ISSUE THREAD

**Issue by Fx-Ren** [gnina/models#24]
An error is reported during file decompression. How to solve the problem?

Archive File：CrossDocked2020_v1.2.tgz
Error Message in Linux：
![image](https://user-images.githubusercontent.com/17877321/191241580-98a170b1-67e3-4002-80fd-eec4f47a1139.png)

Error Message in Windows：
![image](https://user-images.githubusercontent.com/17877321/191241638-542ae6b3-4905-4283-b7a7-628d5713d04d.png)

**Comment by dkoes** [comment]
I've verified the integrity of the tarball on the server.  The md5 hash is:
eeba4cd6c119a24b6b24810122596133

Check your md5sum, if it is different the file probably got corrupted when you downloaded it.

**Comment by Fx-Ren** [comment]
Got it. Thanks very much.
I will re-download the tarball since the md5 hash value of my local tarball is unmatched.
