### ISSUE TITLE
about *.types files

### ISSUE THREAD

**Issue by fe-kim** [gnina/models#3]
Hello,

I tried to make CNN models, but there are some difficulties.

There are various types of '*.types' files, each '*.types' file has N of columns.
In files which have 4 or 5 columns, I don't know meaning of some columns.

For example,
```
A file all.types(data/csar/all.types) has 3 of columns like below.
I know each columns are meaning about label, receptor file, ligand file.
0 set2/102/rec.gninatypes set2/102/docked_17.gninatypes # 6.072250 -5.202670
0 set2/102/rec.gninatypes set2/102/docked_18.gninatypes # 5.235610 -5.080780

A file gaffwmintrain0.types(models/data/general/gaffwmintrain0.types) has 4 columns like below.
In this file, I don't know meaning of 2nd colums.
What is meaning of 2nd column and how I can make this column value?
1 8.0000 9abp/9abp_rec.gninatypes 9abp/9abp_min.gninatypes # -7.90308 0.485643
0 -8.3500 9hvp/9hvp_rec.gninatypes 9hvp/9hvp_ligand_1.gninatypes # -9.82969 4.74258

Also, a file ccv_gen_uff_3_test0.types(models/data/PDBBind2016/General_types/ccv_gen_uff_3_test0.types) has 5 columns like below.
What is meaning of 2nd, 3rd columns and how I can make this columns?
1 3.52 0.880169 4eky/4eky_rec_0.gninatypes 4eky/4eky_min_0.gninatypes # -9.76619
1 3.52 0.69435 4eky/4eky_rec_0.gninatypes 4eky/4eky_docked_0.gninatypes # -11.2589
```

I want to know meaning of all columns from all "*.types" files.
Could you please explain what it is meaning?

Thanks.

**Comment by dkoes** [comment]
The second column is a binding affinity and the third an rmsd.  The MolGridLayer has flags has_affinity and has_rmsd to indicate if these columns exist.  Of course, you use these columns to represent any floating point label.    For maximum flexibility use libmolgrid (https://gnina.github.io/libmolgrid/)

**Comment by fe-kim** [comment]
Thanks a lot for your swift response :)
