### ISSUE TITLE
CrossDocked2020 Pose scores

### ISSUE THREAD

**Issue by ddomingof** [gnina/models#32]
Hi, 
I would like to know where can I find the precalculated scores for all the >20M poses for each ligand-target pair.
Is that in the dump somewhere?
Thanks!

**Comment by dkoes** [comment]
If you want scores from the gnina default ensemble, then no.  @francoep 's imputation paper has data for specific models: https://bits.csb.pitt.edu/files/imputation_paper/

**Comment by ddomingof** [comment]
Pity. Thanks a lot for the pointer!
