### ISSUE TITLE
CASR datebase

### ISSUE THREAD

**Issue by yy2058** [gnina/models#5]
Hello，I'm trying to train cnn model with CASR dataset. But I want to the structure of these pose. I didn't find the sdf files in the CASR folders. Can you share the sdf files of these docked poses with me? this is my email: 2822251409@qq.com. Thank you.

**Comment by dkoes** [comment]
I strongly recommend against using CSAR for training - it is too small.  Use the CrossDck2020 set instead. But the raw data is available here:
http://bits.csb.pitt.edu/files/csardata.tgz

**Comment by yy2058** [comment]
Thank you very much。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 晚上9:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [gnina/models] CASR datebase (#5)





 
I strongly recommend against using CSAR for training - it is too small.  Use the CrossDck2020 set instead. But the raw data is available here:
 http://bits.csb.pitt.edu/files/csardata.tgz
